### ISSUE TITLE
生成 BDF 时出错

### ISSUE THREAD

**Issue by diaowinner** [TakWolf/pixel-font-builder#6]
原项目：[`https://github.com/DWNfonts/Project-Rawya`](https://github.com/DWNfonts/Project-Rawya)
<details>
<summary>

[源代码](https://github.com/DWNfonts/Project-Rawya/blob/develop/make/makepfb.py)节选

</summary>

```python
import os
from pixel_font_builder import (
    FontBuilder,
    StyleName,
    SerifMode,
    WidthMode,
    Glyph,
    opentype,
)
from datetime import datetime
from PIL import Image
from tqdm import tqdm, trange
from os import listdir

if __name__ == "__main__":
    now = datetime.now()
    builder = FontBuilder(12)

    builder.meta_info.version = now.strftime("%y%m%d%H%M%S")
    builder.meta_info.family_name = "Rawya (makepfb.py)"
    builder.meta_info.style_name = StyleName.REGULAR
    builder.meta_info.serif_mode = SerifMode.SANS_SERIF
    builder.meta_info.width_mode = WidthMode.MONOSPACED
    builder.meta_info.manufacturer = "DWNfonts"
    builder.meta_info.designer = "DWNfonts"
    builder.meta_info.description = "Rawya, generated by makepfb.py"
    builder.meta_info.copyright_info = "(c) hicc, DWNfonts, 2023-2024"
    builder.meta_info.license_info = "See license on GitHub"
    builder.meta_info.vendor_url = "https://github.com/DWNfonts/Project-Rawya"
    builder.meta_info.designer_url = "https://github.com/DWNfonts"
    builder.meta_info.license_url = (
        "https://github.com/DWNfonts/Project-Rawya/blob/develop/LICENSE.md"
    )
    builder.meta_info.sample_text = "Hello World!"

    builder.horizontal_header.ascent = 12
    builder.horizontal_header.descent = 0

    builder.vertical_header.ascent = 6
    builder.vertical_header.descent = -6

    builder.os2_config.x_height = 8
    builder.os2_config.cap_height = 10

    部件列表 = listdir("out/")
    print("正在导入字体…")
    for i in trange(len(部件列表)):
        部件 = 部件列表[i]
        编码 = ord(部件.replace(".png", ""))
        builder.character_mapping.update({编码: hex(ord(部件.replace(".png", "")))})
        部件图 = Image.open("out/" + 部件)
        data = []
        for x in range(12):
            line = []
            for y in range(12):
                a = 部件图.getpixel((y, x))[3]
                if a > 0:
                    a = 1
                line.append(a)
            data.append(line)

        builder.glyphs.append(
            Glyph(
                name=hex(ord(部件.replace(".png", ""))),
                advance_width=12,
                advance_height=12,
                horizontal_origin=(0, 0),
                vertical_origin_y=0,
                data=data,
            )
        )

    builder.glyphs.append(
        Glyph(
            name=".notdef",
            advance_width=8,
            advance_height=12,
            horizontal_origin=(0, 0),
            vertical_origin_y=0,
            data=[
                [1, 1, 1, 1, 1, 1, 1, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 0, 0, 0, 0, 0, 0, 1],
                [1, 1, 1, 1, 1, 1, 1, 1],
            ],
        )
    )

    print("正在生成字体…")
    builder.save_otf("rawya.otf")
    builder.save_otf("rawya.woff2", flavor=opentype.Flavor.WOFF2)
    builder.save_ttf("rawya.ttf")
    builder.save_bdf("rawya.bdf")
    builder.save_pcf("rawya.pcf")
```

</details>

```
Traceback (most recent call last):
  File "/home/diaowinner/Project-Rawya/make/makepfb.py", line 101, in <module>
    builder.save_bdf("rawya.bdf")
  File "/home/diaowinner/Project-Rawya/.venv/lib/python3.12/site-packages/pixel_font_builder/font.py", line 75, in save_bdf
    self.to_bdf_builder().save(file_path)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/diaowinner/Project-Rawya/.venv/lib/python3.12/site-packages/pixel_font_builder/font.py", line 72, in to_bdf_builder
    return bdf.create_font(self)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/diaowinner/Project-Rawya/.venv/lib/python3.12/site-packages/pixel_font_builder/bdf.py", line 61, in create_font
    font.glyphs.append(_create_glyph(font_size, config, -1, name_to_glyph['.notdef']))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/diaowinner/Project-Rawya/.venv/lib/python3.12/site-packages/pixel_font_builder/bdf.py", line 32, in _create_glyph
    return BdfGlyph(
           ^^^^^^^^^
TypeError: BdfGlyph.__init__() got an unexpected keyword argument 'code_point'
```

**Comment by TakWolf** [comment]
确保依赖为最新版

```shell 
 pip install --upgrade pixel-font-builder
```

然后考虑该 PR: https://github.com/DWNfonts/Project-Rawya/pull/1

**Comment by diaowinner** [comment]
> 确保依赖为最新版
> 
> ```shell 
>  pip install --upgrade pixel-font-builder
> ```
> 
> 然后考虑该 PR: https://github.com/DWNfonts/Project-Rawya/pull/1

依赖是最新版，我重装了 venv 也有这个 bug  
拉取请求已合并，等我有时间试试

**Comment by TakWolf** [comment]
我不确定你是如何管理依赖的，但是重装  pixel-font-builder 后，如下依赖应该会同步更新：

https://github.com/TakWolf/pixel-font-builder/blob/master/pyproject.toml#L25

```
bdffont>=0.0.25
pcffont>=0.0.13
```

**Comment by diaowinner** [comment]
> 我不确定你是如何管理依赖的，但是重装  pixel-font-builder 后，如下依赖应该会同步更新：
> 
> https://github.com/TakWolf/pixel-font-builder/blob/master/pyproject.toml#L25
> 
> ```
> bdffont>=0.0.25
> pcffont>=0.0.13
> ```

我把整个 venv 重装了一遍，确认这并非系统升级所造成的。
也就是说，这三个依赖都借着重装的机会「更新」了一遍
（等会，我是不是忘写 requirements 了（（

**Comment by TakWolf** [comment]
bdffont  0.0.21  -> 0.0.22 做了不兼容变动：（encoding 更符合文档语意）
https://github.com/TakWolf/bdffont/blob/0.0.21/src/bdffont/glyph.py#L6
https://github.com/TakWolf/bdffont/blob/0.0.22/src/bdffont/glyph.py#L6

所以该错误表示你的环境中这个依赖没有升级，你可以这样检查项目子环境的依赖版本：
![image](https://github.com/TakWolf/pixel-font-builder/assets/6064962/a925996b-8d1e-40a6-b8d9-f87f44c3778a)

**Comment by diaowinner** [comment]
排查了一下，是[吉林大学镜像站](https://mirrors.jlu.edu.cn/)的问题  
![pypi 31 天前 9 分钟后](https://github.com/TakWolf/pixel-font-builder/assets/32033700/095725b5-8f1f-4879-a6a6-0ee4f0a2a853)  
暂时使用[清华大学镜像源](https://mirrors.tuna.tsinghua.edu.cn/help/pypi/)重试，无此问题
